name = "whatsapp-bot"
main = "src/index.ts"
compatibility_date = "2023-03-21"
# node_compat = true
kv_namespaces = [
  { binding = "MESSAGES", id = "53ac8c9dada54f378389875339653c06", preview_id = "81ef9ce5d8374a80a287196aedb28385" }
]

[vars]
ENVIRONMENT = "production"

# [SECRETS]
# - POSTHOG_TOKEN
# - MAYTAPI_PRODUCT
# - MAYTAPI_PHONE
# - MAYTAPI_TOKEN
# => ADD THESE TO YOUR DEPLOYMENT VIA `echo <VALUE> | wrangler secret put <KEY>` for each
